spring:
    profiles:
        active: local # default environment

# local environment
---
spring:
    profiles: local
    jpa:
        show-sql: true
        database: mysql
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update
    h2:
        console:
            enabled: true
    mvc:
        view:
            prefix: /
            suffix: .jsp
    messages:
        basename: validation